default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
#  username: postgres
#  password: pd
#  host: localhost
#  port: 5432

development:
  <<: *default
  database: WarrantyCheck_development

test:
  <<: *default
  database: WarrantyCheck_test

production:
  <<: *default
  database: WarrantyCheck_production
  username: postgres
  password: <%= ENV['WARRANTYCHECK_DATABASE_PASSWORD'] %>
