['registered', 'banned', 'admin'].each do |role|
  Role.find_or_create_by({name: role})
end

Category.create(name: "Electronics")
Category.create(name: "Aooarel & Accessories")
Category.create(name: "Toys & Games")
Category.create(name: "Arts & Entertainment")
Category.create(name: "Health & Beauty")
Category.create(name: "Electrical")
Category.create(name: "Furniture")
Category.create(name: "Vehicles & Parts")
Category.create(name: "Computer Parts")
Category.create(name: "Hardware")
Category.create(name: "Sporting Goods")

Brand.create(name: "Videocon")
Brand.create(name: "Samsung")
Brand.create(name: "LG")
Brand.create(name: "Sony")
Brand.create(name: "Lenovo")
Brand.create(name: "DELL")
Brand.create(name: "Motorola")
Brand.create(name: "Redmi")
Brand.create(name: "HTC")
Brand.create(name: "MI")
Brand.create(name: "VIVO")
Brand.create(name: "Micromax")
Brand.create(name: "VU")
Brand.create(name: "Panasonic")
Brand.create(name: "Philips")
Brand.create(name: "GE")
Brand.create(name: "Luminos")
Brand.create(name: "Exide")
Brand.create(name: "Electrolux")
Brand.create(name: "Fisher Price")
Brand.create(name: "TATA")
Brand.create(name: "Mahindra")
Brand.create(name: "Toyota")
Brand.create(name: "Maruti")
Brand.create(name: "Suzuki")
Brand.create(name: "Honda")
Brand.create(name: "Wipro")
Brand.create(name: "Syska")
Brand.create(name: "Havells")
Brand.create(name: "Chevrolet")
Brand.create(name: "Renault")
Brand.create(name: "TVS")
Brand.create(name: "HP")
Brand.create(name: "Nikon")
Brand.create(name: "Casio")
Brand.create(name: "Timex")
Brand.create(name: "Rado")
Brand.create(name: "Rolex")
Brand.create(name: "Seiko")
Brand.create(name: "Espirit")
Brand.create(name: "Sandisk")
Brand.create(name: "Symtronics")
Brand.create(name: "Apple")
Brand.create(name: "CP Plus")
